### PR TITLE
Onvm clean merge

### PR DESCRIPTION
**Pull request by koolzz**
This pr includes the new commits from the master branch.

New changes from master are now merged into the onvm branch

***Works using onvm dpdk***

### CODE REVIEW

**Comment by nks5295** [comment]
I'm assuming you've tested and verified that mTCP works with and without the ONVM module with this update?

**Comment by koolzz** [comment]
**No,**
This changes dpdk to 17.08, I'm not sure how onvm will behave if we run it with this version of dpdk or how mtcp will behave if we run it with the old 16.11 dpdk version.

I'm planning to test this a after the openNetVM 17.11 update.

**Comment by koolzz** [comment]
So this works, if we use onvm dpdk. If we try to use the new 17.11 version we'll have to update the onvm repo as it breaks some `rte_` method calls

I've had to include `define TCP_FLAGS` to mtcp as onvm also has defs for TCP_FLAGS, so I've added a safety check to prevent compiler errors `ifndef TCP_FLAGS` in `onvm_pkt_helper.h`.

**Comment by koolzz** [comment]
I think this is good to merge as if it breaks I can just delete and redo the `onvm` branch.

**Comment by koolzz** [comment]
As this is a big merge might as well update it to the latest master commit

**Pull request merged**
